### ISSUE TITLE
Makefile not working

### ISSUE THREAD

**Issue by FnugDev** [ouonline/lua-mysql#1]

**Comment by FnugDev** [comment]
Pls update this have spent the last couple of hours trying to figure out how to compile it but still no luck

**Comment by ouonline** [comment]
> Pls update this have spent the last couple of hours trying to figure out how to compile it but still no luck

It works well on my laptop. Please modify the Makefile according to your environment.

**Comment by FnugDev** [comment]
What version of make do u use?

**Comment by FnugDev** [comment]
Actually can u just send me the compiled version? i've spent too long trying to figure out a way

**Comment by RoyvEmpel** [comment]
I have the same problem.

Make 4.2.1
